### ISSUE TITLE
HACS support

### ISSUE THREAD

**Issue by syphernl** [eelcohn/home-assistant-rdw#12]
Could you please add support for HACS? That would make installing / upgrading a lot easier.

**Comment by eelcohn** [comment]
Thanks, I'm aware that the HACS support feature is requested by some of the users, and that it would make installing and upgrading a lot easier. I'm currently working on a major update of the RDW platform which I ultimately want to push to the official Home Assistant Core repository. Therefore I'm not really putting effort in HACS support because I want to push RDW to the main repository.

**Comment by eelcohn** [comment]
Duplicate of #2
