### ISSUE TITLE
Add Community (HACS) support

### ISSUE THREAD

**Issue by Giel538** [eelcohn/home-assistant-rdw#2]
Hi, can you please add HACS support. This well be the new custom updater.

**Comment by metbril** [comment]
More info on how to start

https://hacs.xyz/docs/publish/start

**Comment by eelcohn** [comment]
Thanks, I'm aware that the HACS support feature is requested by some of the users, and that it would make installing and upgrading a lot easier. I'm currently working on a major update of the RDW platform which I ultimately want to push to the official Home Assistant Core repository. Therefore I'm not really putting effort in HACS support because I want to push RDW to the main repository.

**Comment by eelcohn** [comment]
I'll leave this one open as a reminder that this is still a feature request for some of you

**Comment by poudenes** [comment]
Hi Eelcohn, i love the add-on. Not for me but my sister is using it.
any plans to push it into HACS already?

**Comment by metbril** [comment]
Hi @eelcohn. Can you share any update about this feature?

**Comment by JDunnio** [comment]
I was also searching for this. I managed to do it the manual way. I thought that adding and integration to HACS was a matter of placing a few files?

The reason i prefer HACS is because of auto-update on new versions and compatibility with new HA-versions.
If it is not to much effort it would be greatly appreciated if it was available from HACS.

Thanks for this great integration and all the effort put into it!

**Comment by metbril** [comment]
@eelcohn would you mind sharing an update on your progress adding the component to the main repo as you mentioned in https://github.com/eelcohn/home-assistant-rdw/issues/2#issuecomment-591914580 ?

**Comment by TheRedBull205** [comment]
Deleted this integration for now until it's fixed or added to home assistant. Wish I had some more knowledge about python to fix it myself...

**Comment by poudenes** [comment]
> Deleted this integration for now until it's fixed or added to home assistant. Wish I had some more knowledge about python to fix it myself...

If you follow the install method rdw is running perfect in HA.... I have 3 cars now In HA

**Comment by TheRedBull205** [comment]
> 
> 
> > Deleted this integration for now until it's fixed or added to home assistant. Wish I had some more knowledge about python to fix it myself...
> 
> If you follow the install method rdw is running perfect in HA.... I have 3 cars now In HA

Did you use the "YAML" version or the "Integration" to add plates?
Since I run into:
 #32

**Comment by poudenes** [comment]
> > > Deleted this integration for now until it's fixed or added to home assistant. Wish I had some more knowledge about python to fix it myself...
> > 
> > 
> > If you follow the install method rdw is running perfect in HA.... I have 3 cars now In HA
> 
> Did you use the "YAML" version or the "Integration" to add plates?
> Since I run into:
> #32

Im using the integration way to add them

**Comment by nielsklumper** [comment]
I've created a pull request for this: #38 

There's an issue with the config flow though, YAML configuration works fine!

**Comment by eelcohn** [comment]
Fixed in #38

**Comment by eelcohn** [comment]
Thank you for your work @Klumper
